// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HotelBooking.Specs.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Create booking")]
    public partial class CreateBookingFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "create_booking.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Create booking", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
  #line hidden
#line 4
    testRunner.Given("the system is reset to a known empty state", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a valid booking")]
        [NUnit.Framework.CategoryAttribute("happy")]
        public void CreateAValidBooking()
        {
            string[] tagsOfScenario = new string[] {
                    "happy"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a valid booking", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
  this.FeatureBackground();
#line hidden
#line 8
    testRunner.Given("a room type \"double\" exists with capacity 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
    testRunner.And("the date range \"2025-11-10\" to \"2025-11-12\" is available for \"double\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "guestName",
                            "Alice Smith"});
                table1.AddRow(new string[] {
                            "roomType",
                            "double"});
                table1.AddRow(new string[] {
                            "checkIn",
                            "2025-11-10"});
                table1.AddRow(new string[] {
                            "checkOut",
                            "2025-11-12"});
                table1.AddRow(new string[] {
                            "guests",
                            "2"});
#line 10
    testRunner.When("I create a booking with:", ((string)(null)), table1, "When ");
#line hidden
#line 16
    testRunner.Then("the response status should be 201", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 17
    testRunner.And("the booking should exist with totalNights 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 18
    testRunner.And("availability for \"double\" from \"2025-11-10\" to \"2025-11-12\" should be reduced by " +
                        "1 per night", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Reject invalid booking")]
        [NUnit.Framework.CategoryAttribute("validation")]
        [NUnit.Framework.TestCaseAttribute("Alice Smith", "double", "2025-11-12", "2025-11-10", "2", "check-out after check-in", null)]
        [NUnit.Framework.TestCaseAttribute("", "double", "2025-11-10", "2025-11-12", "2", "guestName required", null)]
        [NUnit.Framework.TestCaseAttribute("Bob Jones", "suite", "2025-11-10", "2025-11-12", "5", "exceeds room capacity", null)]
        [NUnit.Framework.TestCaseAttribute("Bob Jones", "double", "2025-11-10", "2025-11-10", "1", "minimum 1 night", null)]
        public void RejectInvalidBooking(string guestName, string roomType, string checkIn, string checkOut, string guests, string error, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "validation"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("guestName", guestName);
            argumentsOfScenario.Add("roomType", roomType);
            argumentsOfScenario.Add("checkIn", checkIn);
            argumentsOfScenario.Add("checkOut", checkOut);
            argumentsOfScenario.Add("guests", guests);
            argumentsOfScenario.Add("error", error);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reject invalid booking", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
  this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "guestName",
                            string.Format("{0}", guestName)});
                table2.AddRow(new string[] {
                            "roomType",
                            string.Format("{0}", roomType)});
                table2.AddRow(new string[] {
                            "checkIn",
                            string.Format("{0}", checkIn)});
                table2.AddRow(new string[] {
                            "checkOut",
                            string.Format("{0}", checkOut)});
                table2.AddRow(new string[] {
                            "guests",
                            string.Format("{0}", guests)});
#line 22
    testRunner.When("I create a booking with:", ((string)(null)), table2, "When ");
#line hidden
#line 28
    testRunner.Then("the response status should be 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 29
    testRunner.And(string.Format("the error message should contain \"{0}\"", error), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Prevent overlapping booking in a full room")]
        [NUnit.Framework.CategoryAttribute("overlap")]
        public void PreventOverlappingBookingInAFullRoom()
        {
            string[] tagsOfScenario = new string[] {
                    "overlap"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Prevent overlapping booking in a full room", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 39
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 3
  this.FeatureBackground();
#line hidden
#line 40
    testRunner.Given("a room type \"double\" exists with capacity 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "guestName",
                            "Jane Roe"});
                table3.AddRow(new string[] {
                            "roomType",
                            "double"});
                table3.AddRow(new string[] {
                            "checkIn",
                            "2025-11-10"});
                table3.AddRow(new string[] {
                            "checkOut",
                            "2025-11-12"});
                table3.AddRow(new string[] {
                            "guests",
                            "1"});
#line 41
    testRunner.And("an existing booking:", ((string)(null)), table3, "And ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "guestName",
                            "John Doe"});
                table4.AddRow(new string[] {
                            "roomType",
                            "double"});
                table4.AddRow(new string[] {
                            "checkIn",
                            "2025-11-11"});
                table4.AddRow(new string[] {
                            "checkOut",
                            "2025-11-13"});
                table4.AddRow(new string[] {
                            "guests",
                            "1"});
#line 47
    testRunner.When("I create a booking with:", ((string)(null)), table4, "When ");
#line hidden
#line 53
    testRunner.Then("the response status should be 409", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 54
    testRunner.And("the error message should contain \"no availability\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
