name: .NET Test Pipeline

on:
  push:
    branches:
      - postman-tests

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release
  
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Web API
        run: dotnet build ./HotelBooking.WebApi/HotelBooking.WebApi/HotelBooking.WebApi.csproj --configuration Release

      - name: Publish Web API
        run: dotnet publish ./HotelBooking.WebApi/HotelBooking.WebApi/HotelBooking.WebApi.csproj -c Release -o ./publish

      - name: Start Web API
        run: |
          dotnet ./publish/HotelBooking.WebApi.dll --urls "http://localhost:5000" &
          sleep 10

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: newman run ./Postman/SoftwareQuality.postman_collection.json -e ./Postman/SoftwareQuality.postman_environment.json
